FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /app
RUN apk update && apk upgrade
RUN apk add --no-cache clang build-base zlib-dev libssl1.1

COPY . .
RUN dotnet publish -c Release

FROM alpine AS runtime
WORKDIR /app
COPY --from=build /app/bin/Release/net8.0/linux-musl-x64/publish/* /app/
CMD ["./name"]
